version: 2.1

workflows:
  build_and_publish:
    jobs:
        - build:
            filters:
              tags:
                only: /.*/
        - publish:
            requires:
              - build
            filters:
              tags:
                only: /v[0-9]+\.[0-9]+\.[0-9]+$/
              branches:
                ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
        - checkout
        - run:
            name: Lint
            command: |
              go vet ./...
              go get -u golang.org/x/lint/golint
              golint ./...
        - run:
            name: Test
            command: go test -v -cover ./...


  publish:
    docker:
      - image: circleci/golang:1.14
    steps:
        - checkout
        - run:
            name: Release
            command: curl -sL https://git.io/goreleaser | bash
