version: 2.1

workflows:
  build_and_publish:
    jobs:
        - build:
            filters:
              tags:
                only: /.*/
        - publish:
            requires:
              - build
            # filters:
            #   tags:
            #     only: /v[0-9]+\.[0-9]+\.[0-9]+$/
            #   branches:
            #     ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
        - checkout
        - restore_cache:
            key: v1-ci-cache-{{ checksum "poetry.lock" }}
        - run:
            name: Install Poetry
            command: |
              python -m pip install --upgrade pip
              pip install poetry
        - run:
            name: Install depdencies
            command: poetry install
        - save_cache:
            key: v1-ci-cache-{{ checksum "poetry.lock" }}
            paths:
              - /home/circleci/.cache/virtualenvs/ratus-py3.7
        - run:
            name: Lint
            command: |
                poetry run black --check ratus
                poetry run isort --check-only
                poetry run mypy ratus
        - run:
            name: Test
            command: poetry run pytest --cov=ratus tests

  publish:
    docker:
      - image: circleci/python:3.8
    steps:
        - checkout
        - restore_cache:
            key: v1-publish-cache-{{ checksum "poetry.lock" }}
        - run:
            name: Install packaging dependencies
            command: |
              python -m pip install --upgrade pip
              pip install poetry
              poetry install
        - save_cache:
            key: v1-publish-cache-{{ checksum "poetry.lock" }}
            paths:
              - /home/circleci/.cache/virtualenvs/ratus-py3.7
        - run:
            name: Build
            command: |
              poetry build
              ls
        - run:
            name: Publish
            command: poetry run python -m twine upload dist/*
